// types generated by quicktype during postinstall phase
import { OpenAttestationDocument as OpenAttestationDocumentV2 } from "../__generated__/schemaV2";
import { OpenAttestationDocument as OpenAttestationDocumentV3 } from "../__generated__/schemaV3";

export type OpenAttestationDocument = OpenAttestationDocumentV2 | OpenAttestationDocumentV3;
export type SignatureProofAlgorithm = "SHA3MerkleProof";

export enum SchemaId {
  v2 = "https://schema.openattestation.com/2.0/schema.json",
  v3 = "https://schema.openattestation.com/3.0/schema.json"
}

export interface Signature {
  type: SignatureProofAlgorithm;
  targetHash: string;
  proof: string[];
  merkleRoot: string;
}

export interface ProofSigningOptions {
  privateKey: string;
  verificationMethod: string;
  type: ProofType;
  proofPurpose?: ProofPurpose;
}

export interface ObfuscationMetadata {
  obfuscatedData?: string[];
}

export interface SchematisedDocument<T extends OpenAttestationDocument = OpenAttestationDocument> {
  version: SchemaId;
  data: DeepStringify<T>;
  schema?: string;
  privacy?: ObfuscationMetadata;
}

export interface WrappedDocument<T extends OpenAttestationDocument = OpenAttestationDocument> {
  version: SchemaId;
  signature: Signature;
  data: DeepStringify<T>;
  schema?: string;
  privacy?: ObfuscationMetadata;
}

export enum ProofType {
  OpenAttestationSignature2018 = "OpenAttestationSignature2018"
}
export enum ProofPurpose {
  AssertionMethod = "assertionMethod"
}
export interface Proof {
  type: ProofType;
  created: string;
  proofPurpose: ProofPurpose;
  verificationMethod: string;
  signature: string;
}
export interface SignedWrappedDocument<T extends OpenAttestationDocument = OpenAttestationDocument>
  extends WrappedDocument<T> {
  proof: Proof[];
}

// feel free to improve, as long as this project compile without changes :)
// once salted, every property is turned into a string
export type DeepStringify<T> = {
  [P in keyof T]: T[P] extends Array<number> // if it's a []number
    ? Array<string> // return []string
    : T[P] extends Array<string> // if it's []string
    ? Array<string> // return []string
    : T[P] extends Record<string, any> // if it's an object
    ? DeepStringify<T[P]> // apply stringify on the object
    : T[P] extends Array<Record<string, infer U>> // if it's an array of object
    ? DeepStringify<U> // apply stringify on the array
    : number extends T[P] // if it's a number
    ? string // make it a string
    : undefined extends T[P] // if it's an optional field
    ? DeepStringify<T[P]> // stringify the type
    : string; // default to string
};
